### ISSUE TITLE
no trapesis

### ISSUE THREAD

**Issue by middatod** [Facel3ss/Simple-Python-Area-Calculator#3]
want trapesius calc

**Comment by ChaoticGooose** [comment]
...STOOOPPPP

**Comment by ChaoticGooose** [comment]
Go write it yourself and raise a pull request, Closed

**Comment by middatod** [comment]
why do you never see elephants hiding in trees

**Comment by middatod** [comment]
because theyre so good at it

**Comment by middatod** [comment]
closed by authority
